### ISSUE TITLE
[REPOSITORY] Grant right to create branches

### ISSUE THREAD

**Issue by juergenhemelt** [odpi/egeria-connector-integration-event-schema#3]
@planetf1 Please grant me (@juergenhemelt) and Darius (@dariusatruvia) the right to create branches in the repository. Thanks!

**Comment by planetf1** [comment]
We use a Git hub fork/pull model for our Egeria repositories, which is common across most open source projects.

Contributors (including maintainers) will fork the repository, work with their own branches, and then submit those changes via a pull request. A maintainer will then review & merge those changes into master (or other releases)

So we don't use branches for regular work. main/master is the main code line, and then we typically create branches on a per release basis. Very occasionally we have also created feature branches where there are complex activities/refactoring going on. Maintainers, or whoever is responsible for the release will do this. This has been one of the core egeria maintainers up to this point, but it's also possible to extend these privilges on a per-repo basis.

Can you describe me about the reasoning for creating branches. Is it for releasing, or something else?

Thanks

**Comment by planetf1** [comment]
http://egeria-project.org/education/tutorials/git-and-git-hub-tutorial/overview

**Comment by juergenhemelt** [comment]
Ok, my mistake. I was on the wrong remote. We have already a fork but I added the odpi-repo as upstream target by mistake.
