### ISSUE TITLE
address review feedback from https://github.com/odpi/egeria-connector-integration-event-schema/pull/5

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-connector-integration-event-schema#7]

**Comment by davidradl** [comment]
@planetf1 I agreed with Juergen to try to merge [https://github.com/odpi/egeria-connector-integration-event-schema/pull/5](https://github.com/odpi/egeria-connector-integration-event-schema/pull/5). I resolved the conversations with the idea they will be addressed in this issue.

2 things are now stopping the merge of the pr:
- the sonatype issues
- getting agreement on what any new copyright content will mean. I am talking with Juergen and will involve LF AI and data legal for advice if there in new copyright lines that are being proposed.

**Comment by planetf1** [comment]
I think the former would ideally be addressed, but not critical.
ensuring we get agreement on copyright is critical prior to merge.

**Comment by juergenhemelt** [comment]
I will change the copyright statement to match the default one of Egeria.

**Comment by juergenhemelt** [comment]
PR has been merged.
